---
- hosts: keystone
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      sudo: yes
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

